import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { 
  Clock, 
  CheckCircle, 
  AlertCircle, 
  User,
  Eye,
  Check,
  X,
  Users,
  DollarSign,
  TrendingUp,
  Calendar,
  Download
} from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { format } from "date-fns";

interface PendingTimesheet {
  id: number;
  userId: number;
  staffName: string;
  staffEmail: string;
  payPeriodStart: string;
  payPeriodEnd: string;
  status: 'submitted' | 'approved' | 'rejected';
  totalHours: string;
  totalEarnings: string;
  submittedAt: string;
  autoSubmitted?: boolean;
}

interface TimesheetEntry {
  id: number;
  entryDate: string;
  startTime: string;
  endTime: string;
  breakMinutes: number;
  totalHours: string;
  hourlyRate: string;
  grossPay: string;
  isAutoGenerated: boolean;
  notes?: string;
  shiftId?: number;
  shiftTitle?: string;
  shiftDescription?: string;
  clientName?: string;
  clientId?: number;
}

interface ReviewStats {
  pendingCount: number;
  totalHours: number;
  totalEarnings: number;
  autoSubmittedCount: number;
}

export default function TimesheetReviewDashboard() {
  const { user } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedTimesheets, setSelectedTimesheets] = useState<number[]>([]);
  const [selectedTimesheet, setSelectedTimesheet] = useState<PendingTimesheet | null>(null);
  const [selectedTimesheetEntries, setSelectedTimesheetEntries] = useState<TimesheetEntry[]>([]);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);

  const { data: pendingTimesheets = [], isLoading } = useQuery<PendingTimesheet[]>({
    queryKey: ["/api/admin/timesheets/pending"],
  });

  const { data: stats } = useQuery<ReviewStats>({
    queryKey: ["/api/admin/timesheets/stats"],
  });

  // Export individual timesheet as PDF
  const exportTimesheetMutation = useMutation({
    mutationFn: async (timesheetId: number) => {
      const response = await fetch(`/api/admin/timesheets/${timesheetId}/export-pdf`);
      if (!response.ok) throw new Error("Failed to export timesheet");
      
      const data = await response.json();
      
      // Generate PDF using the data (simplified for now - returns JSON data)
      const blob = new Blob([JSON.stringify(data, null, 2)], {
        type: 'application/json'
      });
      
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `timesheet-${data.timesheet.userName}-${data.timesheet.payPeriodStart}.json`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Timesheet exported successfully",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to export timesheet",
        variant: "destructive",
      });
    },
  });

  const { data: timesheetEntries = [], refetch: refetchEntries } = useQuery<TimesheetEntry[]>({
    queryKey: ["/api/admin/timesheets", selectedTimesheet?.id, "entries"],
    enabled: !!selectedTimesheet?.id,
  });

  const bulkApproveMutation = useMutation({
    mutationFn: async (timesheetIds: number[]) => {
      return apiRequest("POST", "/api/admin/timesheets/bulk-approve", {
        timesheetIds,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/pending"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/stats"] });
      setSelectedTimesheets([]);
      toast({
        title: "Timesheets Approved",
        description: `Successfully approved ${selectedTimesheets.length} timesheets`,
      });
    },
    onError: (error: any) => {
      toast({
        title: "Approval Failed",
        description: error.message || "Failed to approve timesheets",
        variant: "destructive",
      });
    },
  });

  const approveMutation = useMutation({
    mutationFn: async (timesheetId: number) => {
      return apiRequest("POST", `/api/admin/timesheets/${timesheetId}/approve`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/pending"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/stats"] });
      toast({
        title: "Timesheet Approved",
        description: "Timesheet has been approved successfully",
      });
    },
  });

  const rejectMutation = useMutation({
    mutationFn: async (timesheetId: number) => {
      return apiRequest("POST", `/api/admin/timesheets/${timesheetId}/reject`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/pending"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/timesheets/stats"] });
      toast({
        title: "Timesheet Rejected",
        description: "Timesheet has been rejected",
      });
    },
  });

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedTimesheets(pendingTimesheets.map(t => t.id));
    } else {
      setSelectedTimesheets([]);
    }
  };

  const handleSelectTimesheet = (timesheetId: number, checked: boolean) => {
    if (checked) {
      setSelectedTimesheets(prev => [...prev, timesheetId]);
    } else {
      setSelectedTimesheets(prev => prev.filter(id => id !== timesheetId));
    }
  };

  const getStatusBadge = (status: string, autoSubmitted?: boolean) => {
    const baseClass = "inline-flex items-center gap-1";
    
    switch (status) {
      case 'submitted':
        return (
          <Badge variant="outline" className={`${baseClass} text-blue-700 border-blue-200 bg-blue-50`}>
            <Clock className="h-3 w-3" />
            {autoSubmitted ? 'Auto-Submitted' : 'Submitted'}
          </Badge>
        );
      case 'approved':
        return (
          <Badge variant="outline" className={`${baseClass} text-green-700 border-green-200 bg-green-50`}>
            <CheckCircle className="h-3 w-3" />
            Approved
          </Badge>
        );
      case 'rejected':
        return (
          <Badge variant="outline" className={`${baseClass} text-red-700 border-red-200 bg-red-50`}>
            <X className="h-3 w-3" />
            Rejected
          </Badge>
        );
      default:
        return <Badge variant="secondary">{status}</Badge>;
    }
  };

  const handleViewTimesheet = (timesheet: PendingTimesheet) => {
    setSelectedTimesheet(timesheet);
    setIsViewDialogOpen(true);
  };

  const formatCurrency = (amount: string | number) => {
    const num = typeof amount === 'string' ? parseFloat(amount) : amount;
    return new Intl.NumberFormat('en-AU', {
      style: 'currency',
      currency: 'AUD'
    }).format(num);
  };

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'dd/MM/yyyy');
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {[...Array(4)].map((_, i) => (
            <Card key={i}>
              <CardContent className="p-6">
                <div className="animate-pulse space-y-2">
                  <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                  <div className="h-8 bg-gray-200 rounded w-1/2"></div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="flex items-center p-6">
            <div className="flex items-center">
              <div className="p-2 bg-blue-100 dark:bg-blue-900 rounded-lg">
                <AlertCircle className="h-6 w-6 text-blue-600 dark:text-blue-300" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Pending Review</p>
                <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                  {stats?.pendingCount || 0}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="flex items-center p-6">
            <div className="flex items-center">
              <div className="p-2 bg-green-100 dark:bg-green-900 rounded-lg">
                <Clock className="h-6 w-6 text-green-600 dark:text-green-300" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Total Hours</p>
                <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                  {stats?.totalHours?.toFixed(1) || '0.0'}h
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="flex items-center p-6">
            <div className="flex items-center">
              <div className="p-2 bg-purple-100 dark:bg-purple-900 rounded-lg">
                <DollarSign className="h-6 w-6 text-purple-600 dark:text-purple-300" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Total Payroll</p>
                <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                  ${stats?.totalEarnings?.toFixed(2) || '0.00'}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="flex items-center p-6">
            <div className="flex items-center">
              <div className="p-2 bg-amber-100 dark:bg-amber-900 rounded-lg">
                <TrendingUp className="h-6 w-6 text-amber-600 dark:text-amber-300" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Auto-Submitted</p>
                <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                  {stats?.autoSubmittedCount || 0}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Pending Timesheets */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <Users className="h-5 w-5" />
              Timesheets Awaiting Review
            </CardTitle>
            {selectedTimesheets.length > 0 && (
              <Button
                onClick={() => bulkApproveMutation.mutate(selectedTimesheets)}
                disabled={bulkApproveMutation.isPending}
                className="bg-green-600 hover:bg-green-700"
              >
                <Check className="h-4 w-4 mr-2" />
                Approve Selected ({selectedTimesheets.length})
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent>
          {pendingTimesheets.length === 0 ? (
            <div className="text-center py-12">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">All Caught Up!</h3>
              <p className="text-gray-600">No timesheets pending review at the moment.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-12">
                      <Checkbox
                        checked={selectedTimesheets.length === pendingTimesheets.length}
                        onCheckedChange={handleSelectAll}
                      />
                    </TableHead>
                    <TableHead>Staff Member</TableHead>
                    <TableHead>Pay Period</TableHead>
                    <TableHead>Hours</TableHead>
                    <TableHead>Gross Pay</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Submitted</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {pendingTimesheets.map((timesheet) => (
                    <TableRow key={timesheet.id}>
                      <TableCell>
                        <Checkbox
                          checked={selectedTimesheets.includes(timesheet.id)}
                          onCheckedChange={(checked) => 
                            handleSelectTimesheet(timesheet.id, checked as boolean)
                          }
                        />
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <User className="h-4 w-4 text-slate-400" />
                          <div>
                            <div className="font-medium">{timesheet.staffName}</div>
                            <div className="text-sm text-slate-500">{timesheet.staffEmail}</div>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          <Calendar className="h-4 w-4 inline mr-1" />
                          {format(new Date(timesheet.payPeriodStart), "MMM dd")} - {format(new Date(timesheet.payPeriodEnd), "MMM dd, yyyy")}
                        </div>
                      </TableCell>
                      <TableCell className="font-medium">{timesheet.totalHours}h</TableCell>
                      <TableCell className="font-medium">${timesheet.totalEarnings}</TableCell>
                      <TableCell>{getStatusBadge(timesheet.status, timesheet.autoSubmitted)}</TableCell>
                      <TableCell className="text-sm text-slate-500">
                        {format(new Date(timesheet.submittedAt), "MMM dd, HH:mm")}
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-1 flex-wrap">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setSelectedTimesheet(timesheet);
                              setIsViewDialogOpen(true);
                            }}
                          >
                            <Eye className="h-3 w-3" />
                            View
                          </Button>
                          <Button
                            size="sm"
                            onClick={() => exportTimesheetMutation.mutate(timesheet.id)}
                            disabled={exportTimesheetMutation.isPending}
                            className="bg-blue-600 hover:bg-blue-700"
                          >
                            <Download className="h-3 w-3" />
                            PDF
                          </Button>
                          <Button
                            size="sm"
                            variant="default"
                            onClick={() => approveMutation.mutate(timesheet.id)}
                            disabled={approveMutation.isPending}
                            className="bg-green-600 hover:bg-green-700"
                          >
                            <Check className="h-3 w-3" />
                            Approve
                          </Button>
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() => rejectMutation.mutate(timesheet.id)}
                            disabled={rejectMutation.isPending}
                          >
                            <X className="h-3 w-3" />
                            Reject
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* View Timesheet Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <User className="h-5 w-5" />
              Timesheet Review - {selectedTimesheet?.staffName}
            </DialogTitle>
          </DialogHeader>
          {selectedTimesheet && (
            <div className="space-y-6">
              {/* Timesheet Summary */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 bg-slate-50 rounded-lg">
                <div>
                  <span className="text-sm text-slate-600">Pay Period:</span>
                  <div className="font-medium">
                    {format(new Date(selectedTimesheet.payPeriodStart), "MMM dd")} - {format(new Date(selectedTimesheet.payPeriodEnd), "MMM dd, yyyy")}
                  </div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Total Hours:</span>
                  <div className="font-medium text-lg">{selectedTimesheet.totalHours}h</div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Gross Pay:</span>
                  <div className="font-medium text-lg text-green-600">{formatCurrency(selectedTimesheet.totalEarnings)}</div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Status:</span>
                  <div>{getStatusBadge(selectedTimesheet.status, selectedTimesheet.autoSubmitted)}</div>
                </div>
              </div>

              {/* Individual Shift Earnings - Replicating Support Worker View */}
              <Card className="border-2 border-slate-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Calendar className="h-5 w-5" />
                    Individual Shift Earnings
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {timesheetEntries.length > 0 ? (
                    <div className="overflow-x-auto">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Date</TableHead>
                            <TableHead>Shift</TableHead>
                            <TableHead>Client</TableHead>
                            <TableHead>Hours</TableHead>
                            <TableHead>Rate</TableHead>
                            <TableHead>Earnings</TableHead>
                            <TableHead>Type</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {timesheetEntries.map((entry) => (
                            <TableRow key={entry.id}>
                              <TableCell>{formatDate(entry.entryDate)}</TableCell>
                              <TableCell>
                                <div className="font-medium">{entry.shiftTitle || 'General Shift'}</div>
                                <div className="text-xs text-gray-500">
                                  {entry.startTime && entry.endTime && (
                                    `${format(new Date(entry.startTime), 'h:mm a')} - ${format(new Date(entry.endTime), 'h:mm a')}`
                                  )}
                                </div>
                              </TableCell>
                              <TableCell>
                                <div className="flex items-center gap-2">
                                  <User className="h-4 w-4 text-gray-400" />
                                  {entry.clientName || '-'}
                                </div>
                              </TableCell>
                              <TableCell>
                                <div className="font-medium">{parseFloat(entry.totalHours).toFixed(2)}h</div>
                                {entry.breakMinutes > 0 && (
                                  <div className="text-xs text-gray-500">
                                    -{entry.breakMinutes}min break
                                  </div>
                                )}
                              </TableCell>
                              <TableCell>
                                <div className="font-medium">{formatCurrency(entry.hourlyRate)}/hr</div>
                              </TableCell>
                              <TableCell>
                                <div className="font-medium text-green-600">
                                  {formatCurrency(entry.grossPay)}
                                </div>
                              </TableCell>
                              <TableCell>
                                <Badge variant={entry.isAutoGenerated ? "default" : "secondary"}>
                                  {entry.isAutoGenerated ? "Auto" : "Manual"}
                                </Badge>
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  ) : (
                    <div className="text-center py-8 text-gray-500">
                      <Calendar className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                      <p>No timesheet entries found for this period</p>
                    </div>
                  )}
                </CardContent>
              </Card>
              
              {/* Action Buttons */}
              <div className="flex gap-3 pt-4 border-t">
                <Button
                  onClick={() => {
                    approveMutation.mutate(selectedTimesheet.id);
                    setIsViewDialogOpen(false);
                  }}
                  disabled={approveMutation.isPending}
                  className="bg-green-600 hover:bg-green-700 flex-1"
                >
                  <Check className="h-4 w-4 mr-2" />
                  {approveMutation.isPending ? 'Approving...' : 'Approve Timesheet'}
                </Button>
                <Button
                  variant="destructive"
                  onClick={() => {
                    rejectMutation.mutate(selectedTimesheet.id);
                    setIsViewDialogOpen(false);
                  }}
                  disabled={rejectMutation.isPending}
                  className="flex-1"
                >
                  <X className="h-4 w-4 mr-2" />
                  {rejectMutation.isPending ? 'Rejecting...' : 'Reject Timesheet'}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}