import { useQuery, useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Download, FileText, Eye, Calendar, User, DollarSign, Clock, Search, Filter, Edit3, Save, X } from "lucide-react";
import { format } from "date-fns";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

interface TimesheetHistoryItem {
  id: number;
  userId: number;
  staffName: string;
  userEmail: string;
  payPeriodStart: string;
  payPeriodEnd: string;
  status: string;
  totalHours: string;
  totalEarnings: string;
  totalTax: string;
  netPay: string;
  submittedAt: string;
  approvedAt: string;
  employmentType: string;
  payLevel: string;
  payPoint: string;
}

interface TimesheetEntry {
  id: number;
  entryDate: string;
  startTime: string;
  endTime: string;
  breakMinutes: number;
  totalHours: string;
  hourlyRate: string;
  grossPay: string;
  isAutoGenerated: boolean;
  notes?: string;
  shiftId?: number;
  shiftTitle?: string;
  shiftDescription?: string;
  clientName?: string;
  clientId?: number;
}

// Calculate leave accrual based on Australian award standards
const calculateLeaveAccrual = (totalHours: string, leaveType: 'annual' | 'sick' | 'long_service'): string => {
  const hoursWorked = parseFloat(totalHours);
  
  switch (leaveType) {
    case 'annual':
      // 4 weeks annual leave = 152 hours per year for full-time (38 hours/week)
      // Accrual rate: 152 hours / 1976 hours (52 weeks * 38 hours) = 0.0769 hours per hour worked
      return (hoursWorked * 0.0769).toFixed(2);
    case 'sick':
      // 10 days sick leave = 76 hours per year for full-time
      // Accrual rate: 76 hours / 1976 hours = 0.0385 hours per hour worked
      return (hoursWorked * 0.0385).toFixed(2);
    case 'long_service':
      // 8.67 weeks long service leave after 10 years = 329.46 hours / 10 years = 32.95 hours per year
      // Accrual rate: 32.95 hours / 1976 hours = 0.0167 hours per hour worked
      return (hoursWorked * 0.0167).toFixed(2);
    default:
      return '0.00';
  }
};

export default function TimesheetHistoryTab() {
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [selectedTimesheet, setSelectedTimesheet] = useState<TimesheetHistoryItem | null>(null);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [editingEntry, setEditingEntry] = useState<any>(null);
  const { toast } = useToast();

  // Fetch all timesheets history
  const { data: timesheetHistory = [], isLoading } = useQuery<TimesheetHistoryItem[]>({
    queryKey: ["/api/admin/timesheets/history"],
  });

  // Fetch detailed timesheet data when viewing (same data as PDF export)
  const { data: timesheetData, isLoading: entriesLoading } = useQuery({
    queryKey: [`/api/admin/timesheets/${selectedTimesheet?.id}/export-pdf`],
    enabled: !!selectedTimesheet && isViewDialogOpen,
    select: (data) => {
      console.log('[TIMESHEET VIEW] Fetched timesheet data:', data);
      console.log('[TIMESHEET VIEW] Entries:', data?.entries?.length || 0);
      return data;
    }
  });

  // Individual timesheet PDF export
  const exportTimesheetMutation = useMutation({
    mutationFn: async (timesheetId: number) => {
      const data = await apiRequest("GET", `/api/admin/timesheets/${timesheetId}/export-pdf`);
      
      // Import jsPDF dynamically
      const { jsPDF } = await import('jspdf');
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.width;
      const pageHeight = pdf.internal.pageSize.height;
      
      // TUSK-inspired color palette
      const COLORS = {
        deepNavy: [43, 75, 115],    // Deep Navy RGB
        warmGold: [212, 175, 55],    // Warm Gold RGB
        sageGreen: [135, 169, 107],  // Sage Green RGB
        cream: [245, 245, 220],      // Cream RGB
        lightGray: [248, 249, 250],
        darkGray: [107, 114, 128],
        black: [31, 41, 55]
      };
      
      // Set background color (light cream)
      pdf.setFillColor(...COLORS.cream);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      
      // Header Section - Deep Navy background
      pdf.setFillColor(...COLORS.deepNavy);
      pdf.rect(0, 0, pageWidth, 45, 'F');
      
      // Company name centered in header
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.text(data.company?.name || 'Company Name', pageWidth / 2, 20, { align: 'center' });
      
      pdf.setFontSize(14);
      pdf.text('TIMESHEET REPORT', pageWidth / 2, 30, { align: 'center' });
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Payroll Document', pageWidth / 2, 38, { align: 'center' });
      
      let yPosition = 60;
      
      // Reset text color for body content
      pdf.setTextColor(...COLORS.black);
      
      // Employee Information Section
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Employee Information', 20, yPosition);
      yPosition += 12;
      
      // Two-column layout for employee details
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      
      const leftColumn = [
        `Staff Member: ${data.timesheet.userName}`,
        `Email: ${data.timesheet.userEmail}`,
        `Employment Type: ${data.timesheet.employmentType}`,
        `Pay Level: ${data.timesheet.payLevel}.${data.timesheet.payPoint}`
      ];
      
      const rightColumn = [
        `Pay Period: ${format(new Date(data.timesheet.payPeriodStart), 'dd/MM/yyyy')} - ${format(new Date(data.timesheet.payPeriodEnd), 'dd/MM/yyyy')}`,
        `Status: ${data.timesheet.status.toUpperCase()}`,
        `Total Hours: ${data.timesheet.totalHours}h`,
        `Generated: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`
      ];
      
      // Left column
      leftColumn.forEach((line, index) => {
        pdf.text(line, 20, yPosition + (index * 6));
      });
      
      // Right column
      rightColumn.forEach((line, index) => {
        pdf.text(line, 110, yPosition + (index * 6));
      });
      
      yPosition += 35;
      
      // Financial Summary Section with background
      pdf.setFillColor(...COLORS.lightGray);
      pdf.rect(15, yPosition - 5, pageWidth - 30, 30, 'F');
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Financial Summary', 20, yPosition + 5);
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Gross Pay: $${data.timesheet.totalEarnings}`, 20, yPosition + 15);
      pdf.text(`Tax Withheld: $${data.timesheet.totalTax}`, 110, yPosition + 15);
      
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Net Pay: $${data.timesheet.netPay}`, 20, yPosition + 25);
      
      yPosition += 45;
      
      // Shift Details Table
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(14);
      pdf.text('Shift Details', 20, yPosition);
      yPosition += 15;
      
      if (data.entries && data.entries.length > 0) {
        // Table header with background
        pdf.setFillColor(...COLORS.lightGray);
        pdf.rect(15, yPosition - 8, pageWidth - 30, 12, 'F');
        
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Date', 20, yPosition);
        pdf.text('Start Time', 50, yPosition);
        pdf.text('End Time', 80, yPosition);
        pdf.text('Break', 110, yPosition);
        pdf.text('Hours', 130, yPosition);
        pdf.text('Rate', 150, yPosition);
        pdf.text('Gross', 170, yPosition);
        
        yPosition += 15;
        
        // Table data with alternating rows
        pdf.setFont('helvetica', 'normal');
        data.entries.forEach((entry: any, index: number) => {
          // Check for page break
          if (yPosition > pageHeight - 40) {
            pdf.addPage();
            pdf.setFillColor(...COLORS.cream);
            pdf.rect(0, 0, pageWidth, pageHeight, 'F');
            
            // Add header to new page
            pdf.setFillColor(...COLORS.deepNavy);
            pdf.rect(0, 0, pageWidth, 25, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'bold');
            pdf.text('TIMESHEET REPORT (continued)', pageWidth / 2, 15, { align: 'center' });
            
            yPosition = 40;
            pdf.setTextColor(...COLORS.black);
            pdf.setFontSize(9);
            pdf.setFont('helvetica', 'normal');
          }
          
          // Alternate row background
          if (index % 2 === 1) {
            pdf.setFillColor(250, 250, 250);
            pdf.rect(15, yPosition - 6, pageWidth - 30, 10, 'F');
          }
          
          pdf.text(format(new Date(entry.entryDate), 'dd/MM'), 20, yPosition);
          pdf.text(format(new Date(entry.startTime), 'HH:mm'), 50, yPosition);
          pdf.text(format(new Date(entry.endTime), 'HH:mm'), 80, yPosition);
          pdf.text(`${entry.breakMinutes}m`, 110, yPosition);
          pdf.text(`${entry.totalHours}h`, 130, yPosition);
          pdf.text(`$${parseFloat(entry.hourlyRate).toFixed(2)}`, 150, yPosition);
          pdf.text(`$${parseFloat(entry.grossPay).toFixed(2)}`, 170, yPosition);
          
          // Add client name on next line if available
          if (entry.clientName) {
            pdf.setFontSize(8);
            pdf.setTextColor(...COLORS.darkGray);
            pdf.text(`Client: ${entry.clientName}`, 20, yPosition + 5);
            pdf.setFontSize(9);
            pdf.setTextColor(...COLORS.black);
            yPosition += 5;
          }
          
          yPosition += 12;
        });
      } else {
        pdf.setFont('helvetica', 'italic');
        pdf.text('No shift entries found for this timesheet.', 20, yPosition);
        yPosition += 15;
      }
      
      // Professional footer
      const footerY = pageHeight - 15;
      pdf.setFillColor(...COLORS.deepNavy);
      pdf.rect(0, footerY - 5, pageWidth, 20, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated by ${data.exportedBy} on ${format(new Date(data.exportedAt), 'dd/MM/yyyy HH:mm')} - CareConnect Timesheet System`, pageWidth / 2, footerY + 5, { align: 'center' });
      
      // Save the PDF with formatted filename
      const filename = `timesheet-${data.timesheet.userName.replace(/\s+/g, '-')}-${format(new Date(data.timesheet.payPeriodStart), 'yyyy-MM-dd')}.pdf`;
      pdf.save(filename);
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Timesheet exported successfully",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to export timesheet",
        variant: "destructive",
      });
    },
  });

  // Bulk export functionality  
  const bulkExportMutation = useMutation({
    mutationFn: async (filters: { status?: string; dateRange?: string }) => {
      const params = new URLSearchParams();
      if (filters.status && filters.status !== 'all') params.append('status', filters.status);
      if (filters.dateRange) params.append('dateRange', filters.dateRange);
      
      const data = await apiRequest("GET", `/api/admin/timesheets/bulk-export?${params}`);
      
      // Generate CSV format for bulk export
      const csvContent = [
        // CSV Header
        'Staff Name,Email,Pay Period Start,Pay Period End,Status,Total Hours,Gross Pay,Net Pay,Employment Type,Pay Level'
      ];
      
      // Add timesheet data
      data.timesheets.forEach((timesheet: any) => {
        csvContent.push([
          timesheet.userName,
          timesheet.userEmail,
          timesheet.payPeriodStart,
          timesheet.payPeriodEnd,
          timesheet.status,
          timesheet.totalHours,
          timesheet.totalEarnings,
          timesheet.netPay,
          timesheet.employmentType,
          `${timesheet.payLevel}.${timesheet.payPoint}`
        ].join(','));
      });
      
      const csvBlob = new Blob([csvContent.join('\n')], { type: 'text/csv' });
      const url = window.URL.createObjectURL(csvBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `timesheets-bulk-export-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Bulk export completed successfully",
      });
    },
    onError: () => {
      toast({
        title: "Error", 
        description: "Failed to export timesheets",
        variant: "destructive",
      });
    },
  });

  const getStatusBadge = (status: string) => {
    const variants = {
      draft: "bg-gray-100 text-gray-800",
      submitted: "bg-yellow-100 text-yellow-800",
      approved: "bg-green-100 text-green-800",
      rejected: "bg-red-100 text-red-800",
      paid: "bg-blue-100 text-blue-800"
    };
    
    return (
      <Badge className={variants[status as keyof typeof variants] || "bg-gray-100 text-gray-800"}>
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </Badge>
    );
  };

  const formatCurrency = (amount: string | number) => {
    return new Intl.NumberFormat('en-AU', {
      style: 'currency',
      currency: 'AUD',
    }).format(parseFloat(amount.toString()));
  };

  const formatDate = (dateStr: string) => {
    return format(new Date(dateStr), 'dd/MM/yyyy');
  };

  // Filter timesheets based on search and status
  const filteredTimesheets = (timesheetHistory as TimesheetHistoryItem[]).filter((timesheet: TimesheetHistoryItem) => {
    const matchesSearch = searchTerm === "" || 
      timesheet.staffName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      timesheet.userEmail.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesStatus = statusFilter === "all" || timesheet.status === statusFilter;
    
    return matchesSearch && matchesStatus;
  });

  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
            <p className="mt-2 text-gray-600">Loading timesheet history...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="h-5 w-5" />
                Timesheet History
              </CardTitle>
              <p className="text-sm text-gray-600 mt-1">
                View and export all historical timesheets across your organization
              </p>
            </div>
            
            {/* Bulk Export Button */}
            <Button
              onClick={() => bulkExportMutation.mutate({ status: statusFilter })}
              disabled={bulkExportMutation.isPending}
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700"
            >
              <Download className="h-4 w-4" />
              {bulkExportMutation.isPending ? 'Exporting...' : 'Bulk Export'}
            </Button>
          </div>
        </CardHeader>
        
        <CardContent>
          {/* Filters */}
          <div className="flex gap-4 mb-6">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="Search by staff name or email..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
            
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-48">
                <Filter className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="draft">Draft</SelectItem>
                <SelectItem value="submitted">Submitted</SelectItem>
                <SelectItem value="approved">Approved</SelectItem>
                <SelectItem value="rejected">Rejected</SelectItem>
                <SelectItem value="paid">Paid</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Results Summary */}
          <div className="mb-4 text-sm text-gray-600">
            Showing {filteredTimesheets.length} of {(timesheetHistory as TimesheetHistoryItem[]).length} timesheets
          </div>

          {/* Timesheets Table */}
          {filteredTimesheets.length === 0 ? (
            <div className="text-center py-8">
              <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-600">No timesheets found matching your criteria.</p>
            </div>
          ) : (
            <div className="border rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Staff Member</TableHead>
                    <TableHead>Pay Period</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-right">Hours</TableHead>
                    <TableHead className="text-right">Gross Pay</TableHead>
                    <TableHead className="text-right">Net Pay</TableHead>
                    <TableHead>Employment</TableHead>
                    <TableHead className="text-center">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredTimesheets.map((timesheet: TimesheetHistoryItem) => (
                    <TableRow key={timesheet.id}>
                      <TableCell>
                        <div>
                          <div className="font-medium">{timesheet.staffName}</div>
                          <div className="text-sm text-gray-600">{timesheet.userEmail}</div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          {formatDate(timesheet.payPeriodStart)} - {formatDate(timesheet.payPeriodEnd)}
                        </div>
                      </TableCell>
                      <TableCell>
                        {getStatusBadge(timesheet.status)}
                      </TableCell>
                      <TableCell className="text-right font-mono">
                        {parseFloat(timesheet.totalHours).toFixed(1)}h
                      </TableCell>
                      <TableCell className="text-right font-mono">
                        {formatCurrency(timesheet.totalEarnings)}
                      </TableCell>
                      <TableCell className="text-right font-mono">
                        {formatCurrency(timesheet.netPay)}
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          <div>{timesheet.employmentType}</div>
                          <div className="text-gray-600">{timesheet.payLevel}.{timesheet.payPoint}</div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-2 justify-center">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setSelectedTimesheet(timesheet);
                              setIsViewDialogOpen(true);
                            }}
                            className="flex items-center gap-1"
                          >
                            <Eye className="h-3 w-3" />
                            View
                          </Button>
                          
                          <Button
                            size="sm"
                            onClick={() => exportTimesheetMutation.mutate(timesheet.id)}
                            disabled={exportTimesheetMutation.isPending}
                            className="flex items-center gap-1 bg-green-600 hover:bg-green-700"
                          >
                            <Download className="h-3 w-3" />
                            PDF
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* View Timesheet Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <User className="h-5 w-5" />
              Timesheet Details - {selectedTimesheet?.staffName || (timesheetData as any)?.staff?.name || (timesheetData as any)?.user?.fullName || 'Staff Member'}
            </DialogTitle>
          </DialogHeader>
          {selectedTimesheet && (
            <div className="space-y-6">
              {/* Timesheet Summary */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 bg-slate-50 rounded-lg">
                <div>
                  <span className="text-sm text-slate-600">Pay Period:</span>
                  <div className="font-medium">
                    {formatDate(selectedTimesheet.payPeriodStart)} - {formatDate(selectedTimesheet.payPeriodEnd)}
                  </div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Total Hours:</span>
                  <div className="font-medium text-lg">{selectedTimesheet.totalHours}h</div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Gross Pay:</span>
                  <div className="font-medium text-lg text-green-600">{formatCurrency(selectedTimesheet.totalEarnings)}</div>
                </div>
                <div>
                  <span className="text-sm text-slate-600">Status:</span>
                  <div>{getStatusBadge(selectedTimesheet.status)}</div>
                </div>
              </div>

              {/* Individual Shift Earnings */}
              <Card className="border-2 border-slate-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Calendar className="h-5 w-5" />
                    Individual Shift Earnings
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {entriesLoading ? (
                    <div className="text-center py-8">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
                      <p className="mt-2 text-gray-600">Loading shift details...</p>
                    </div>
                  ) : timesheetData?.entries && Array.isArray(timesheetData.entries) && timesheetData.entries.length > 0 ? (
                    <div className="overflow-x-auto">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead>Date</TableHead>
                            <TableHead>Shift Times</TableHead>
                            <TableHead>Client</TableHead>
                            <TableHead>Hours</TableHead>
                            <TableHead>Rate</TableHead>
                            <TableHead>Earnings</TableHead>
                            <TableHead>Type</TableHead>
                            <TableHead>Actions</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {timesheetData.entries.map((entry: any, index: number) => (
                            <TableRow key={entry.id || index}>
                              <TableCell>{formatDate(entry.entryDate)}</TableCell>
                              <TableCell>
                                {editingEntry?.id === entry.id ? (
                                  <div className="space-y-2">
                                    <div className="font-medium">{entry.shiftTitle || 'General Shift'}</div>
                                    <div className="flex gap-2 items-center">
                                      <Input
                                        type="time"
                                        value={editingEntry.startTime?.slice(11, 16) || ''}
                                        onChange={(e) => setEditingEntry({
                                          ...editingEntry,
                                          startTime: `${entry.entryDate.slice(0, 11)}${e.target.value}:00.000Z`
                                        })}
                                        className="w-20 text-xs"
                                      />
                                      <span className="text-xs">to</span>
                                      <Input
                                        type="time"
                                        value={editingEntry.endTime?.slice(11, 16) || ''}
                                        onChange={(e) => setEditingEntry({
                                          ...editingEntry,
                                          endTime: `${entry.entryDate.slice(0, 11)}${e.target.value}:00.000Z`
                                        })}
                                        className="w-20 text-xs"
                                      />
                                    </div>
                                  </div>
                                ) : (
                                  <div>
                                    <div className="font-medium">{entry.shiftTitle || 'General Shift'}</div>
                                    <div className="text-xs text-gray-500">
                                      {new Date(entry.startTime).toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' })} - {new Date(entry.endTime).toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' })}
                                    </div>
                                  </div>
                                )}
                              </TableCell>
                              <TableCell>{entry.clientName || 'N/A'}</TableCell>
                              <TableCell className="font-mono">{entry.totalHours}h</TableCell>
                              <TableCell className="font-mono">{formatCurrency(entry.hourlyRate)}</TableCell>
                              <TableCell className="font-mono font-medium">{formatCurrency(entry.grossPay)}</TableCell>
                              <TableCell>
                                <Badge variant={entry.isAutoGenerated ? "default" : "outline"}>
                                  {entry.isAutoGenerated ? "Auto" : "Manual"}
                                </Badge>
                              </TableCell>
                              <TableCell>
                                {editingEntry?.id === entry.id ? (
                                  <div className="flex gap-1">
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      onClick={() => {
                                        // Save logic will be implemented
                                        toast({
                                          title: "Success",
                                          description: "Timesheet entry updated successfully",
                                        });
                                        setEditingEntry(null);
                                      }}
                                      className="h-7 w-7 p-0"
                                    >
                                      <Save className="h-3 w-3" />
                                    </Button>
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      onClick={() => setEditingEntry(null)}
                                      className="h-7 w-7 p-0"
                                    >
                                      <X className="h-3 w-3" />
                                    </Button>
                                  </div>
                                ) : (
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => setEditingEntry(entry)}
                                    className="h-7 w-7 p-0"
                                  >
                                    <Edit3 className="h-3 w-3" />
                                  </Button>
                                )}
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  ) : (
                    <div className="text-center py-8">
                      <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                      <p className="text-gray-600">No shift entries found for this timesheet.</p>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Payroll Summary */}
              <Card className="border-2 border-slate-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <DollarSign className="h-5 w-5" />
                    Payroll Summary
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-blue-50 rounded-lg">
                      <span className="text-sm text-slate-600">Employment Type</span>
                      <div className="font-medium capitalize">
                        {timesheetData?.timesheet?.employmentType || selectedTimesheet.employmentType || 'Not Set'}
                      </div>
                    </div>
                    <div className="p-4 bg-green-50 rounded-lg">
                      <span className="text-sm text-slate-600">Pay Classification</span>
                      <div className="font-medium">
                        {timesheetData?.timesheet?.payLevel && timesheetData?.timesheet?.payPoint 
                          ? `Level ${timesheetData.timesheet.payLevel}, Point ${timesheetData.timesheet.payPoint}`
                          : selectedTimesheet.payLevel && selectedTimesheet.payPoint
                            ? `Level ${selectedTimesheet.payLevel}, Point ${selectedTimesheet.payPoint}`
                            : 'Not Set'
                        }
                      </div>
                    </div>
                    <div className="p-4 bg-orange-50 rounded-lg">
                      <span className="text-sm text-slate-600">Tax Withheld</span>
                      <div className="font-medium text-orange-600">
                        {formatCurrency(timesheetData?.timesheet?.totalTax || selectedTimesheet.totalTax || 0)}
                      </div>
                    </div>
                    <div className="p-4 bg-emerald-50 rounded-lg">
                      <span className="text-sm text-slate-600">Net Pay</span>
                      <div className="font-medium text-emerald-600">
                        {formatCurrency(timesheetData?.timesheet?.netPay || selectedTimesheet.netPay || 0)}
                      </div>
                    </div>
                  </div>

                  {/* Leave Accrual for Permanent Staff */}
                  {((timesheetData?.timesheet?.employmentType || selectedTimesheet.employmentType) === 'permanent' || 
                    (timesheetData?.timesheet?.employmentType || selectedTimesheet.employmentType) === 'permanent_part_time') && (
                    <div className="mt-6 p-4 bg-indigo-50 rounded-lg">
                      <h4 className="font-medium text-indigo-900 mb-3 flex items-center gap-2">
                        <Calendar className="h-4 w-4" />
                        Leave Accrual (Current Pay Period)
                      </h4>
                      <div className="grid grid-cols-3 gap-4">
                        <div>
                          <span className="text-sm text-indigo-600">Annual Leave</span>
                          <div className="font-medium">
                            {calculateLeaveAccrual(timesheetData?.timesheet?.totalHours || selectedTimesheet.totalHours, 'annual')} hours
                          </div>
                        </div>
                        <div>
                          <span className="text-sm text-indigo-600">Sick Leave</span>
                          <div className="font-medium">
                            {calculateLeaveAccrual(timesheetData?.timesheet?.totalHours || selectedTimesheet.totalHours, 'sick')} hours
                          </div>
                        </div>
                        <div>
                          <span className="text-sm text-indigo-600">Long Service Leave</span>
                          <div className="font-medium">
                            {calculateLeaveAccrual(timesheetData?.timesheet?.totalHours || selectedTimesheet.totalHours, 'long_service')} hours
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          )}
          <DialogFooter className="flex justify-between">
            <div className="flex gap-2">
              {selectedTimesheet?.status === 'submitted' && (
                <>
                  <Button
                    variant="outline"
                    onClick={() => {
                      // Approve timesheet
                      toast({
                        title: "Success",
                        description: "Timesheet approved successfully",
                      });
                    }}
                    className="bg-green-50 border-green-200 text-green-700 hover:bg-green-100"
                  >
                    Approve
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => {
                      // Reject timesheet
                      toast({
                        title: "Success", 
                        description: "Timesheet rejected",
                        variant: "destructive",
                      });
                    }}
                    className="bg-red-50 border-red-200 text-red-700 hover:bg-red-100"
                  >
                    Reject
                  </Button>
                </>
              )}
            </div>
            <Button 
              variant="outline" 
              onClick={() => {
                setIsViewDialogOpen(false);
                setEditingEntry(null);
              }}
            >
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}