import { pgTable, text, serial, integer, boolean, timestamp, jsonb, decimal } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Companies table
export const companies = pgTable("companies", {
  id: text("id").primaryKey(), // UUID generated by crypto.randomUUID()
  name: text("name").notNull(),
  businessAddress: text("business_address"),
  registrationNumber: text("registration_number"),
  primaryContactName: text("primary_contact_name").notNull(),
  primaryContactEmail: text("primary_contact_email").notNull(),
  primaryContactPhone: text("primary_contact_phone"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Tenants table
export const tenants = pgTable("tenants", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  settings: jsonb("settings").default({}),
  companyId: text("company_id").references(() => companies.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Users table with tenant association
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  email: text("email"),
  fullName: text("full_name").notNull(),
  role: text("role").notNull().default("staff"), // admin, staff, viewer
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  isActive: boolean("is_active").default(true),
  isFirstLogin: boolean("is_first_login").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Clients table
export const clients = pgTable("clients", {
  id: serial("id").primaryKey(),
  fullName: text("full_name").notNull(),
  ndisNumber: text("ndis_number"),
  dateOfBirth: timestamp("date_of_birth"),
  phone: text("phone"),
  email: text("email"),
  address: text("address"),
  careLevel: text("care_level"), // independent, assisted, memory_care
  emergencyContact: text("emergency_contact"),
  medicalInfo: text("medical_info"),
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  createdBy: integer("created_by").notNull().references(() => users.id),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Form templates table
export const formTemplates = pgTable("form_templates", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  fields: jsonb("fields").notNull().default([]),
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  createdBy: integer("created_by").notNull().references(() => users.id),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Form submissions table
export const formSubmissions = pgTable("form_submissions", {
  id: serial("id").primaryKey(),
  templateId: integer("template_id").notNull().references(() => formTemplates.id),
  clientId: integer("client_id").references(() => clients.id),
  submittedBy: integer("submitted_by").notNull().references(() => users.id),
  data: jsonb("data").notNull().default({}),
  status: text("status").notNull().default("completed"), // pending, completed
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Shifts table
export const shifts = pgTable("shifts", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id), // Made nullable for unassigned shifts
  clientId: integer("client_id").references(() => clients.id),
  title: text("title"),
  description: text("description"),
  startTime: timestamp("start_time").notNull(),
  endTime: timestamp("end_time"),
  status: text("status").default("assigned"), // assigned, requested, in-progress, completed, cancelled
  location: text("location"),
  latitude: decimal("latitude", { precision: 10, scale: 8 }),
  longitude: decimal("longitude", { precision: 11, scale: 8 }),
  building: text("building"),
  floor: text("floor"),
  // Shift tracking fields
  startTimestamp: timestamp("start_timestamp"),
  endTimestamp: timestamp("end_timestamp"),
  startLocation: text("start_location"),
  endLocation: text("end_location"),
  handoverReceivedFromStaffId: integer("handover_received_from_staff_id").references(() => users.id),
  handoverGivenToStaffId: integer("handover_given_to_staff_id").references(() => users.id),
  handoverNotesIn: text("handover_notes_in"),
  handoverNotesOut: text("handover_notes_out"),
  isActive: boolean("is_active").default(true),
  seriesId: text("series_id"), // For grouping recurring shifts
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Staff Availability table
export const staffAvailability = pgTable("staff_availability", {
  id: serial("id").primaryKey(),
  availabilityId: text("availability_id").notNull().unique(),
  userId: integer("user_id").notNull().references(() => users.id),
  companyId: integer("company_id").notNull().references(() => tenants.id),
  availableDays: jsonb("available_days").notNull(), // ["Monday", "Tuesday", ...]
  timeSlots: jsonb("time_slots").notNull(), // {Monday: {start: "09:00", end: "17:00"}, ...}
  recurrencePattern: text("recurrence_pattern").default("weekly"), // weekly, fortnightly, monthly
  overrideByManager: boolean("override_by_manager").default(false),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Case Notes table
export const caseNotes = pgTable("case_notes", {
  id: serial("id").primaryKey(),
  clientId: integer("client_id").notNull().references(() => clients.id),
  userId: integer("user_id").notNull().references(() => users.id),
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  title: text("title").notNull(),
  content: text("content").notNull(),
  type: text("type").notNull().default("standard"), // standard, incident, medication
  category: text("category").notNull().default("Progress Note"),
  priority: text("priority").notNull().default("normal"), // normal, high, urgent
  tags: text("tags").array().default([]),
  linkedShiftId: integer("linked_shift_id").references(() => shifts.id),
  incidentData: jsonb("incident_data"),
  medicationData: jsonb("medication_data"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Hourly Observations table
export const hourlyObservations = pgTable("hourly_observations", {
  id: serial("id").primaryKey(),
  clientId: integer("client_id").notNull().references(() => clients.id),
  userId: integer("user_id").notNull().references(() => users.id),
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  observationType: text("observation_type").notNull(), // behaviour, adl, health, social, communication
  subtype: text("subtype"), // specific subcategory based on type
  notes: text("notes").notNull(),
  intensity: integer("intensity"), // 1-5 for behaviour observations
  timestamp: timestamp("timestamp").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Activity logs table
export const activityLogs = pgTable("activity_logs", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  action: text("action").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: integer("resource_id"),
  description: text("description").notNull(),
  metadata: jsonb("metadata").default({}),
  tenantId: integer("tenant_id").notNull().references(() => tenants.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Relations
export const companiesRelations = relations(companies, ({ many }) => ({
  tenants: many(tenants),
}));

export const tenantsRelations = relations(tenants, ({ one, many }) => ({
  company: one(companies, {
    fields: [tenants.companyId],
    references: [companies.id],
  }),
  users: many(users),
  clients: many(clients),
  formTemplates: many(formTemplates),
  formSubmissions: many(formSubmissions),
  shifts: many(shifts),
  staffAvailability: many(staffAvailability),
  caseNotes: many(caseNotes),
  activityLogs: many(activityLogs),
}));

export const usersRelations = relations(users, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [users.tenantId],
    references: [tenants.id],
  }),
  createdClients: many(clients),
  createdFormTemplates: many(formTemplates),
  formSubmissions: many(formSubmissions),
  shifts: many(shifts),
  availability: many(staffAvailability),
  caseNotes: many(caseNotes),
  activityLogs: many(activityLogs),
  observations: many(hourlyObservations),
}));

export const clientsRelations = relations(clients, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [clients.tenantId],
    references: [tenants.id],
  }),
  createdBy: one(users, {
    fields: [clients.createdBy],
    references: [users.id],
  }),
  formSubmissions: many(formSubmissions),
  caseNotes: many(caseNotes),
  shifts: many(shifts),
  observations: many(hourlyObservations),
}));

export const formTemplatesRelations = relations(formTemplates, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [formTemplates.tenantId],
    references: [tenants.id],
  }),
  createdBy: one(users, {
    fields: [formTemplates.createdBy],
    references: [users.id],
  }),
  submissions: many(formSubmissions),
}));

export const formSubmissionsRelations = relations(formSubmissions, ({ one }) => ({
  template: one(formTemplates, {
    fields: [formSubmissions.templateId],
    references: [formTemplates.id],
  }),
  client: one(clients, {
    fields: [formSubmissions.clientId],
    references: [clients.id],
  }),
  submittedBy: one(users, {
    fields: [formSubmissions.submittedBy],
    references: [users.id],
  }),
  tenant: one(tenants, {
    fields: [formSubmissions.tenantId],
    references: [tenants.id],
  }),
}));

export const shiftsRelations = relations(shifts, ({ one, many }) => ({
  user: one(users, {
    fields: [shifts.userId],
    references: [users.id],
  }),
  client: one(clients, {
    fields: [shifts.clientId],
    references: [clients.id],
  }),
  tenant: one(tenants, {
    fields: [shifts.tenantId],
    references: [tenants.id],
  }),
  linkedCaseNotes: many(caseNotes),
}));

export const caseNotesRelations = relations(caseNotes, ({ one }) => ({
  client: one(clients, {
    fields: [caseNotes.clientId],
    references: [clients.id],
  }),
  user: one(users, {
    fields: [caseNotes.userId],
    references: [users.id],
  }),
  tenant: one(tenants, {
    fields: [caseNotes.tenantId],
    references: [tenants.id],
  }),
  linkedShift: one(shifts, {
    fields: [caseNotes.linkedShiftId],
    references: [shifts.id],
  }),
}));

export const staffAvailabilityRelations = relations(staffAvailability, ({ one }) => ({
  user: one(users, {
    fields: [staffAvailability.userId],
    references: [users.id],
  }),
  company: one(tenants, {
    fields: [staffAvailability.companyId],
    references: [tenants.id],
  }),
}));

export const hourlyObservationsRelations = relations(hourlyObservations, ({ one }) => ({
  client: one(clients, {
    fields: [hourlyObservations.clientId],
    references: [clients.id],
  }),
  user: one(users, {
    fields: [hourlyObservations.userId],
    references: [users.id],
  }),
  tenant: one(tenants, {
    fields: [hourlyObservations.tenantId],
    references: [tenants.id],
  }),
}));

export const activityLogsRelations = relations(activityLogs, ({ one }) => ({
  user: one(users, {
    fields: [activityLogs.userId],
    references: [users.id],
  }),
  tenant: one(tenants, {
    fields: [activityLogs.tenantId],
    references: [tenants.id],
  }),
}));

// Insert schemas
export const insertCompanySchema = createInsertSchema(companies).omit({
  id: true,
  createdAt: true,
});

export const insertTenantSchema = createInsertSchema(tenants).omit({
  id: true,
  createdAt: true,
});

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
});

export const insertClientSchema = createInsertSchema(clients).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertFormTemplateSchema = createInsertSchema(formTemplates).omit({
  id: true,
  createdAt: true,
});

export const insertFormSubmissionSchema = createInsertSchema(formSubmissions).omit({
  id: true,
  createdAt: true,
});

export const insertShiftSchema = createInsertSchema(shifts).omit({
  id: true,
  createdAt: true,
});

export const insertStaffAvailabilitySchema = createInsertSchema(staffAvailability).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertCaseNoteSchema = createInsertSchema(caseNotes).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertHourlyObservationSchema = createInsertSchema(hourlyObservations).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertActivityLogSchema = createInsertSchema(activityLogs).omit({
  id: true,
  createdAt: true,
});

// Types
export type Company = typeof companies.$inferSelect;
export type InsertCompany = z.infer<typeof insertCompanySchema>;

export type Tenant = typeof tenants.$inferSelect;
export type InsertTenant = z.infer<typeof insertTenantSchema>;

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export type Client = typeof clients.$inferSelect;
export type InsertClient = z.infer<typeof insertClientSchema>;

export type FormTemplate = typeof formTemplates.$inferSelect;
export type InsertFormTemplate = z.infer<typeof insertFormTemplateSchema>;

export type FormSubmission = typeof formSubmissions.$inferSelect;
export type InsertFormSubmission = z.infer<typeof insertFormSubmissionSchema>;

export type Shift = typeof shifts.$inferSelect;
export type InsertShift = z.infer<typeof insertShiftSchema>;

export type StaffAvailability = typeof staffAvailability.$inferSelect;
export type InsertStaffAvailability = z.infer<typeof insertStaffAvailabilitySchema>;

export type CaseNote = typeof caseNotes.$inferSelect;
export type InsertCaseNote = z.infer<typeof insertCaseNoteSchema>;

export type HourlyObservation = typeof hourlyObservations.$inferSelect;
export type InsertHourlyObservation = z.infer<typeof insertHourlyObservationSchema>;

export type ActivityLog = typeof activityLogs.$inferSelect;
export type InsertActivityLog = z.infer<typeof insertActivityLogSchema>;
